name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/github-action-key
          chmod 600 ~/.ssh/github-action-key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-action-key
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          git config --global core.sshCommand "ssh -i ~/.ssh/github-action-key"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/Vaanijyashala-Backend
            git pull origin main
            npm install
            pm2 restart ./bin/www
